name: problem_solving_kib
description: There is a csv file that keeps a record of n order details for orders made at an online  shopping website.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  file_picker: ^5.0.1
  csv: ^5.0.1
  path_provider: ^2.0.11
  permission_handler: ^9.2.0
  share_plus: ^4.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1


flutter:
  uses-material-design: true


